In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('Crime-Prediction-Dataset-1.csv')
data.head(5)

YEAR  SNATCHING  THEFT  ROBERRY  WOMEN HARASSMENT  CHEATING  FRAUD  \
0  2001         12     12       12                 6         9      9   
1  2001          8      8        8                 6         8      8   
2  2001         10     10       10                 6         9      9   
3  2001          9      9        9                 8         7      7   
4  2001         10     10       10                 8         7      7   

   CHILD ABUSE  ATTEMPT TO MURDER  RAPE           STATE  
0            8                  8    10        Gulistan  
1            7                  7    11     Mohammadpur  
2            8                  8     9  Old Town Dhaka  
3            8                  8     8          Mirpur  
4            7                  7     9        Farmgate

In [3]:
# ei khane data ke 2 way te devide korbo
# input multiple hbe but output sudu ekta tai hbe

real_x = data.iloc[:,:10].values
real_y = data.iloc[:,10].values

# ekhon Data ke I/O and O/P er modde Devide korbo

In [4]:
real_x

array([[2001,   12,   12,   12,    6,    9,    9,    8,    8,   10],
       [2001,    8,    8,    8,    6,    8,    8,    7,    7,   11],
       [2001,   10,   10,   10,    6,    9,    9,    8,    8,    9],
       [2001,    9,    9,    9,    8,    7,    7,    8,    8,    8],
       [2001,   10,   10,   10,    8,    7,    7,    7,    7,    9],
       [2001,   12,   12,   12,    6,   12,   12,   10,    7,    8],
       [2001,    9,    9,    9,    7,   11,   11,    6,    6,   10],
       [2001,    9,    9,    9,    8,    7,    7,    7,    7,    9],
       [2001,    8,    8,    8,   10,    5,    5,    7,    9,    8],
       [2001,    9,    9,    9,   10,   10,   10,    7,    7,    7],
       [2001,   10,   10,   10,   10,    6,    6,    8,    8,    9],
       [2001,    8,    8,    8,    7,    7,    7,    8,    8,    9],
       [2001,    8,    8,    8,    9,    8,    8,    8,    7,    8],
       [2002,    9,    9,    9,    6,    9,    9,    8,    8,   10],
       [2002,    8,    8,    8,   

In [5]:
real_y

array(['Gulistan', 'Mohammadpur', 'Old Town Dhaka', 'Mirpur', 'Farmgate',
       'Dhanmondi', 'Bonani', 'Gulshan', 'Elephand Road', 'Khilgaon',
       'Azimpur', 'Badda', 'Luxibazar', 'Gulistan', 'Mohammadpur',
       'Old Town Dhaka', 'Mirpur', 'Farmgate', 'Dhanmondi', 'Bonani',
       'Gulshan', 'Elephand Road', 'Khilgaon', 'Azimpur', 'Badda',
       'Luxibazar', 'Gulistan', 'Mohammadpur', 'Old Town Dhaka', 'Mirpur',
       'Farmgate', 'Dhanmondi', 'Bonani', 'Gulshan', 'Elephand Road',
       'Khilgaon', 'Azimpur', 'Badda', 'Luxibazar', 'Gulistan',
       'Mohammadpur', 'Old Town Dhaka', 'Mirpur', 'Farmgate', 'Dhanmondi',
       'Bonani', 'Gulshan', 'Elephand Road', 'Khilgaon', 'Azimpur',
       'Badda', 'Luxibazar', 'Gulistan', 'Mohammadpur', 'Old Town Dhaka',
       'Mirpur', 'Farmgate', 'Dhanmondi', 'Bonani', 'Gulshan',
       'Elephand Road', 'Khilgaon', 'Azimpur', 'Badda', 'Luxibazar',
       'Gulistan', 'Mohammadpur', 'Old Town Dhaka', 'Mirpur', 'Farmgate',
       'Dhanmondi', 

In [6]:
from sklearn.model_selection import train_test_split # aage eta use hotw-->from sklearn.cross_validation import train_test_split
training_x,testing_x,training_y,testing_y = train_test_split(real_x,real_y,test_size = 0.20, random_state=0)

# I/O or O/P e Data ke Split korbo

In [7]:
training_x

array([[2004,   10,   10,   10,    8,    7,    7,    7,    7,    9],
       [2005,   10,   10,   10,   10,    6,    6,    8,    8,    9],
       [2001,    9,    9,    9,    8,    7,    7,    8,    8,    8],
       [2006,    7,    7,    7,    7,   11,   11,    6,    6,    8],
       [2004,    9,    9,    9,    7,   11,   11,    6,    6,   10],
       [2004,    9,    9,    9,   10,   10,   10,    7,    7,    7],
       [2001,    9,    9,    9,    7,   11,   11,    6,    6,   10],
       [2008,    8,    8,    8,    8,    7,    7,    7,    7,    9],
       [2007,    8,    8,    8,    8,    7,    7,    7,    7,   10],
       [2006,    8,    8,    8,    7,    7,    7,    8,    8,    9],
       [2005,    7,    7,    7,   10,    5,    5,    7,    9,    9],
       [2007,    9,    9,    9,    6,    9,    9,    8,    8,    6],
       [2007,    8,    8,    8,    7,    7,    7,    8,    8,    9],
       [2006,    5,    5,    5,    8,   10,   10,    8,    8,    7],
       [2004,    8,    8,    8,   

In [8]:
testing_x

array([[2003,    6,    6,    6,    6,    9,    9,    8,    8,   10],
       [2007,    7,    7,    7,   10,    5,    5,    7,    9,    9],
       [2001,   10,   10,   10,    6,    9,    9,    8,    8,    9],
       [2005,    8,    8,    8,    8,   10,   10,    8,    8,    7],
       [2006,   10,   10,   10,   10,    6,    6,    8,    8,    9],
       [2008,    6,    7,    8,    6,    5,    5,    7,    7,   10],
       [2002,    9,    9,    9,    8,    7,    7,    8,    8,    8],
       [2006,    7,    7,    7,   10,    5,    5,    7,    9,    9],
       [2005,   10,   10,   10,    6,    9,    9,    8,    8,    5],
       [2008,   10,    5,    8,    8,   10,   10,    8,    8,    7],
       [2005,    8,    8,    8,    6,    5,    5,    7,    7,   10],
       [2008,    9,    9,    9,    6,    7,    7,    8,    8,    9],
       [2007,    7,    7,    7,    6,    7,    7,    8,    8,    9],
       [2002,    9,    9,    9,    6,    9,    9,    8,    8,   10],
       [2001,    9,    9,    9,   

In [9]:
from sklearn.svm import SVC

In [10]:
cls_svc = SVC(kernel='linear', random_state = 0)
cls_svc.fit(training_x,training_y)

SVC(kernel='linear', random_state=0)

In [11]:
y_pred = cls_svc.predict(testing_x)
y_pred # Prediction er value

array(['Badda', 'Elephand Road', 'Old Town Dhaka', 'Mirpur', 'Azimpur',
       'Mohammadpur', 'Mirpur', 'Elephand Road', 'Old Town Dhaka',
       'Mirpur', 'Mohammadpur', 'Badda', 'Gulistan', 'Old Town Dhaka',
       'Farmgate', 'Farmgate', 'Khilgaon', 'Badda', 'Farmgate',
       'Elephand Road'], dtype=object)

In [12]:
testing_y # real

array(['Gulistan', 'Elephand Road', 'Old Town Dhaka', 'Mirpur', 'Azimpur',
       'Mohammadpur', 'Mirpur', 'Elephand Road', 'Old Town Dhaka',
       'Mirpur', 'Mohammadpur', 'Gulistan', 'Gulistan', 'Gulistan',
       'Gulshan', 'Farmgate', 'Khilgaon', 'Badda', 'Gulshan',
       'Elephand Road'], dtype=object)

# Confusion Matrix

In [13]:
from sklearn.metrics import confusion_matrix

In [14]:
confus_matrix = confusion_matrix(testing_y,y_pred)  # y_true = Real Value, y_pred = Prediction er value
confus_matrix

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 1, 0, 0, 0, 0, 1],
       [0, 0, 0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 2]], dtype=int64)

# Accuracy

In [15]:
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(testing_y, y_pred))

Accuracy :  0.75


In [16]:
print (accuracy_score(testing_y, y_pred)*100) # Accuracy

75.0


# precision, recall, f1-score, support


In [17]:
from sklearn.metrics import classification_report
print(classification_report(testing_y, y_pred))

                precision    recall  f1-score   support

       Azimpur       1.00      1.00      1.00         1
         Badda       0.33      1.00      0.50         1
 Elephand Road       1.00      1.00      1.00         3
      Farmgate       0.33      1.00      0.50         1
      Gulistan       1.00      0.25      0.40         4
       Gulshan       0.00      0.00      0.00         2
      Khilgaon       1.00      1.00      1.00         1
        Mirpur       1.00      1.00      1.00         3
   Mohammadpur       1.00      1.00      1.00         2
Old Town Dhaka       0.67      1.00      0.80         2

      accuracy                           0.75        20
     macro avg       0.73      0.82      0.72        20
  weighted avg       0.80      0.75      0.71        20



C:\Users\Nayeem\.conda\envs\tensorflow 3_7\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
