In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('Crime-Prediction-Dataset-1.csv')
data.head(5)

YEAR  SNATCHING  THEFT  ROBERRY  WOMEN HARASSMENT  CHEATING  FRAUD  \
0  2001         12     12       12                 6         9      9   
1  2001          8      8        8                 6         8      8   
2  2001         10     10       10                 6         9      9   
3  2001          9      9        9                 8         7      7   
4  2001         10     10       10                 8         7      7   

   CHILD ABUSE  ATTEMPT TO MURDER  RAPE           STATE  
0            8                  8    10        Gulistan  
1            7                  7    11     Mohammadpur  
2            8                  8     9  Old Town Dhaka  
3            8                  8     8          Mirpur  
4            7                  7     9        Farmgate

In [3]:
# ei khane data ke 2 way te devide korbo
# input multiple hbe but output sudu ekta tai hbe

real_x = data.iloc[:,:10].values
real_y = data.iloc[:,10].values

In [4]:
real_x

array([[2001,   12,   12,   12,    6,    9,    9,    8,    8,   10],
       [2001,    8,    8,    8,    6,    8,    8,    7,    7,   11],
       [2001,   10,   10,   10,    6,    9,    9,    8,    8,    9],
       [2001,    9,    9,    9,    8,    7,    7,    8,    8,    8],
       [2001,   10,   10,   10,    8,    7,    7,    7,    7,    9],
       [2001,   12,   12,   12,    6,   12,   12,   10,    7,    8],
       [2001,    9,    9,    9,    7,   11,   11,    6,    6,   10],
       [2001,    9,    9,    9,    8,    7,    7,    7,    7,    9],
       [2001,    8,    8,    8,   10,    5,    5,    7,    9,    8],
       [2001,    9,    9,    9,   10,   10,   10,    7,    7,    7],
       [2001,   10,   10,   10,   10,    6,    6,    8,    8,    9],
       [2001,    8,    8,    8,    7,    7,    7,    8,    8,    9],
       [2001,    8,    8,    8,    9,    8,    8,    8,    7,    8],
       [2002,    9,    9,    9,    6,    9,    9,    8,    8,   10],
       [2002,    8,    8,    8,   

In [5]:
real_y

array(['Gulistan', 'Mohammadpur', 'Old Town Dhaka', 'Mirpur', 'Farmgate',
       'Dhanmondi', 'Bonani', 'Gulshan', 'Elephand Road', 'Khilgaon',
       'Azimpur', 'Badda', 'Luxibazar', 'Gulistan', 'Mohammadpur',
       'Old Town Dhaka', 'Mirpur', 'Farmgate', 'Dhanmondi', 'Bonani',
       'Gulshan', 'Elephand Road', 'Khilgaon', 'Azimpur', 'Badda',
       'Luxibazar', 'Gulistan', 'Mohammadpur', 'Old Town Dhaka', 'Mirpur',
       'Farmgate', 'Dhanmondi', 'Bonani', 'Gulshan', 'Elephand Road',
       'Khilgaon', 'Azimpur', 'Badda', 'Luxibazar', 'Gulistan',
       'Mohammadpur', 'Old Town Dhaka', 'Mirpur', 'Farmgate', 'Dhanmondi',
       'Bonani', 'Gulshan', 'Elephand Road', 'Khilgaon', 'Azimpur',
       'Badda', 'Luxibazar', 'Gulistan', 'Mohammadpur', 'Old Town Dhaka',
       'Mirpur', 'Farmgate', 'Dhanmondi', 'Bonani', 'Gulshan',
       'Elephand Road', 'Khilgaon', 'Azimpur', 'Badda', 'Luxibazar',
       'Gulistan', 'Mohammadpur', 'Old Town Dhaka', 'Mirpur', 'Farmgate',
       'Dhanmondi', 

In [6]:
#from sklearn import tree

In [7]:
#classify1 = tree.DecisionTreeClassifier()

In [8]:
#classify1 = classify1.fit(real_x,real_y)

In [9]:
#prediction_disease = classify1.predict([[1,0,0,0,0,0,1,0,1,0,0,1,0,1,0,0,0,0,0]])

In [10]:
#prediction_disease

In [11]:
#prediction_disease = classify1.predict([[0,1,1,0,0,0,0,0,1,1,1,1,0,0,0,0,0,1,0]])

In [12]:
#prediction_disease

In [13]:
# Supervised learning e ... dataset -->> traing ar testing dataset e divided kora hoy
# training er data ... 70-80 % rakte hbe er theke besi ora kom hote parbe na 
# testing er data ... baki % e rakbo


from sklearn.model_selection import train_test_split  # divide korar jonno library
training_x,testing_x,training_y,testing_y = train_test_split(real_x,real_y,test_size = 0.25,random_state = 0)  # data set split kortesi
            # randodm_state = 0 na dile ans ekbar ekta asbo 



In [14]:
testing_x

array([[2003,    6,    6,    6,    6,    9,    9,    8,    8,   10],
       [2007,    7,    7,    7,   10,    5,    5,    7,    9,    9],
       [2001,   10,   10,   10,    6,    9,    9,    8,    8,    9],
       [2005,    8,    8,    8,    8,   10,   10,    8,    8,    7],
       [2006,   10,   10,   10,   10,    6,    6,    8,    8,    9],
       [2008,    6,    7,    8,    6,    5,    5,    7,    7,   10],
       [2002,    9,    9,    9,    8,    7,    7,    8,    8,    8],
       [2006,    7,    7,    7,   10,    5,    5,    7,    9,    9],
       [2005,   10,   10,   10,    6,    9,    9,    8,    8,    5],
       [2008,   10,    5,    8,    8,   10,   10,    8,    8,    7],
       [2005,    8,    8,    8,    6,    5,    5,    7,    7,   10],
       [2008,    9,    9,    9,    6,    7,    7,    8,    8,    9],
       [2007,    7,    7,    7,    6,    7,    7,    8,    8,    9],
       [2002,    9,    9,    9,    6,    9,    9,    8,    8,   10],
       [2001,    9,    9,    9,   

In [15]:
training_x

array([[2004,    9,    9,    9,   10,   10,   10,    7,    7,    7],
       [2001,    9,    9,    9,    7,   11,   11,    6,    6,   10],
       [2008,    8,    8,    8,    8,    7,    7,    7,    7,    9],
       [2007,    8,    8,    8,    8,    7,    7,    7,    7,   10],
       [2006,    8,    8,    8,    7,    7,    7,    8,    8,    9],
       [2005,    7,    7,    7,   10,    5,    5,    7,    9,    9],
       [2007,    9,    9,    9,    6,    9,    9,    8,    8,    6],
       [2007,    8,    8,    8,    7,    7,    7,    8,    8,    9],
       [2006,    5,    5,    5,    8,   10,   10,    8,    8,    7],
       [2004,    8,    8,    8,    9,    8,    8,    8,    7,    8],
       [2003,    8,    8,    8,    6,    8,    8,    7,    7,   11],
       [2002,   12,   12,   12,    6,   12,   12,   10,    7,    8],
       [2005,    7,    7,    7,    8,    7,    7,    7,    7,    8],
       [2005,    8,    8,    8,    7,    7,    7,    8,    8,    9],
       [2006,    9,    9,    9,   

In [16]:
from sklearn import tree

In [17]:
classify1 = tree.DecisionTreeClassifier()

In [18]:
classify1 = classify1.fit(training_x,training_y)

In [19]:
testing_y # real Value

array(['Gulistan', 'Elephand Road', 'Old Town Dhaka', 'Mirpur', 'Azimpur',
       'Mohammadpur', 'Mirpur', 'Elephand Road', 'Old Town Dhaka',
       'Mirpur', 'Mohammadpur', 'Gulistan', 'Gulistan', 'Gulistan',
       'Gulshan', 'Farmgate', 'Khilgaon', 'Badda', 'Gulshan',
       'Elephand Road', 'Farmgate', 'Azimpur', 'Mirpur', 'Bonani',
       'Bonani'], dtype=object)

In [20]:
Pred_y = classify1.predict(testing_x)
Pred_y 

array(['Old Town Dhaka', 'Elephand Road', 'Old Town Dhaka', 'Mirpur',
       'Azimpur', 'Mohammadpur', 'Mirpur', 'Elephand Road',
       'Old Town Dhaka', 'Mirpur', 'Mohammadpur', 'Gulistan', 'Gulistan',
       'Old Town Dhaka', 'Gulshan', 'Farmgate', 'Khilgaon', 'Badda',
       'Gulshan', 'Elephand Road', 'Farmgate', 'Azimpur', 'Mirpur',
       'Bonani', 'Bonani'], dtype=object)

# confus_matrix

In [21]:
from sklearn.metrics import confusion_matrix

In [22]:
confus_matrix = confusion_matrix(testing_y,Pred_y)  # y_true = Real Value, y_pred = Prediction er value
confus_matrix

array([[2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2],
       [0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2]], dtype=int64)

# Accuracy

In [23]:
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(testing_y,Pred_y))

Accuracy :  0.92


In [24]:
print (accuracy_score(testing_y,Pred_y)*100) # Accuracy

92.0


# precision, recall, f1-score, support

In [25]:
from sklearn.metrics import classification_report
print(classification_report(testing_y,Pred_y))

                precision    recall  f1-score   support

       Azimpur       1.00      1.00      1.00         2
         Badda       1.00      1.00      1.00         1
        Bonani       1.00      1.00      1.00         2
 Elephand Road       1.00      1.00      1.00         3
      Farmgate       1.00      1.00      1.00         2
      Gulistan       1.00      0.50      0.67         4
       Gulshan       1.00      1.00      1.00         2
      Khilgaon       1.00      1.00      1.00         1
        Mirpur       1.00      1.00      1.00         4
   Mohammadpur       1.00      1.00      1.00         2
Old Town Dhaka       0.50      1.00      0.67         2

      accuracy                           0.92        25
     macro avg       0.95      0.95      0.94        25
  weighted avg       0.96      0.92      0.92        25

